name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Export web build
        env:
          EXPO_PUBLIC_SUPABASE_URL: 'https://ehrkdqsfelynlqlbmfhq.supabase.co'
          EXPO_PUBLIC_SUPABASE_ANON_KEY: 'sb_publishable_WAA5mbMiPpwCm4-sctJ6qA_gMQ38er9'
        run: npx expo export --platform web

      - name: Fix Routing and Disable Jekyll
        run: |
          touch dist/.nojekyll
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
